# Generated by Django 5.2.2 on 2025-07-05 11:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='mother',
            name='age',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='location',
        ),
        migrations.AddField(
            model_name='mother',
            name='address',
            field=models.TextField(default='Raipur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mother',
            name='delivery_date',
            field=models.DateField(default='2025-07-07'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mother',
            name='geolocation',
            field=models.CharField(default='Raipur', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mother',
            name='health_center',
            field=models.CharField(default='Sejbahar', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mother',
            name='phone',
            field=models.CharField(default='9109672075', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mother',
            name='pledge_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pledges/'),
        ),
        migrations.AddField(
            model_name='mother',
            name='pledge_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mother',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Sapling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(choices=[('Aam', 'Aam'), ('Amrood', 'Amrood'), ('Aanwla', 'Aanwla'), ('Papita', 'Papita'), ('Munga', 'Munga')], max_length=50)),
                ('planted_date', models.DateField()),
                ('geolocation', models.CharField(max_length=255)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saplings', to='core.mother')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField()),
                ('reminder_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('sent_to', models.CharField(max_length=255)),
                ('sapling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.sapling')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='sapling_photos/')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('week_number', models.PositiveIntegerField()),
                ('geotag_verified', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.healthworker')),
                ('sapling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.sapling')),
            ],
        ),
    ]
