# Generated by Django 5.2.2 on 2025-07-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_healthworker_remove_mother_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapling',
            name='plant_type',
            field=models.CharField(choices=[('Mango', 'Mango'), ('Guava', 'Guava'), ('Indian Gooseberry', 'Indian Gooseberry'), ('Papaya', 'Papaya'), ('Drumstick', 'Drumstick')], max_length=50),
        ),
    ]
