# Generated by Django 5.2.2 on 2025-07-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sapling_plant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoupload',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='photoupload',
            name='sapling',
        ),
        migrations.RemoveField(
            model_name='reminderlog',
            name='sapling',
        ),
        migrations.DeleteModel(
            name='HealthWorker',
        ),
        migrations.DeleteModel(
            name='PhotoUpload',
        ),
        migrations.DeleteModel(
            name='ReminderLog',
        ),
    ]
