# Generated by Django 5.2.2 on 2025-07-05 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_photoupload_uploaded_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='sapling_photos/')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('week_number', models.PositiveIntegerField(blank=True, null=True)),
                ('geotag_verified', models.BooleanField(default=False)),
                ('sapling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.sapling')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.healthworker')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField(auto_now_add=True)),
                ('reminder_type', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('message', models.TextField()),
                ('sent_to', models.CharField(max_length=100)),
                ('sapling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.sapling')),
            ],
        ),
    ]
